# Generated by Django 4.2.23 on 2025-10-08 02:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0021_alter_addcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/'),
        ),
        migrations.AlterField(
            model_name='i',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image/'),
        ),
    ]
