# Generated by Django 4.2.23 on 2025-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipcart', '0021_alter_addcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
